#!/usr/bin/env bash
#
# handoff-check.sh — did the next actor actually work from the handoff?
#
# A handoff that nobody reads is not a handoff. HANDOFF.md carries a handoff_id: a hash of
# its own content, generated by `ctx.sh handoff`. It exists nowhere else — not in the
# register, not in any chat. The implementer's return must quote it. If the quoted ID
# matches, the implementer read this file. If it does not, it worked from somewhere else.
#
# This also recomputes the ID from the file's content, so a handoff edited by hand after it
# was generated is rejected: a handoff is a projection of durable state, not a scratchpad.
#
# usage: scripts/handoff-check.sh "<the implementer's return, or just its HANDOFF_ID line>"
#        scripts/handoff-check.sh - < return.txt
# exit 0 consumed · 1 not consumed / mismatch · 3 no or malformed handoff

set -uo pipefail
cd "$(dirname "$0")/.." || exit 3

HANDOFF=".workflow/HANDOFF.md"
CONSUMED=".workflow/handoff-consumed"

[ -f "$HANDOFF" ] || { echo "handoff-check: no $HANDOFF — generate one with ./scripts/ctx.sh handoff" >&2; exit 3; }

RECORDED="$(sed -n 's/^handoff_id: *//p' "$HANDOFF" | head -1)"
[ -n "$RECORDED" ] || { echo "handoff-check: $HANDOFF has no handoff_id line — malformed" >&2; exit 3; }

hash12() {
  if command -v shasum >/dev/null 2>&1; then shasum | cut -c1-12
  elif command -v sha256sum >/dev/null 2>&1; then sha256sum | cut -c1-12
  else cksum | tr -d ' \n' | cut -c1-12; fi
}
BODY="$(sed "s/^handoff_id: .*/handoff_id: @@ID@@/" "$HANDOFF")"
EXPECTED="H-$(printf '%s' "$BODY" | hash12)"
if [ "$EXPECTED" != "$RECORDED" ]; then
  echo "handoff-check: $HANDOFF was edited after it was generated (content no longer matches" >&2
  echo "its handoff_id). Regenerate it from the register: ./scripts/ctx.sh handoff ..." >&2
  rm -f "$CONSUMED"
  exit 3
fi

if [ "${1:-}" = "-" ]; then RETURN="$(cat)"; else RETURN="${1:-}"; fi
[ -n "$RETURN" ] || { echo "usage: handoff-check.sh \"<implementer return>\"" >&2; exit 3; }

QUOTED="$(printf '%s\n' "$RETURN" | grep -oE 'HANDOFF_ID:[[:space:]]*H-[0-9a-f]+' | head -1 | grep -oE 'H-[0-9a-f]+')"

if [ -z "$QUOTED" ]; then
  echo "NOT CONSUMED — the return quotes no HANDOFF_ID. There is no evidence the implementer"
  echo "read $HANDOFF."
  rm -f "$CONSUMED"
  exit 1
fi
if [ "$QUOTED" != "$RECORDED" ]; then
  echo "NOT CONSUMED — the return quotes $QUOTED, but $HANDOFF is $RECORDED."
  echo "The implementer worked from a different (stale or invented) handoff."
  rm -f "$CONSUMED"
  exit 1
fi

printf '%s' "$RECORDED" > "$CONSUMED"
echo "CONSUMED — the implementer quoted $RECORDED, which exists only in $HANDOFF."
